[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
multiline_func_header_style = "params_first"
